server:
  port: 8082

spring:
  redis:
    host: localhost
    port: 6379
#  application:
#    name: ratelimiter-example
#  cloud:
#    gateway:
#      routes:
#        - id: route1
#          uri: http://localhost:8081/**
#          predicates:
#            - Path=/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedTokens: 1